create database twinte_course_service;
create database twinte_timetable_service;
create database twinte_school_calendar_service;
create database twinte_donation_service;
create database twinte_information_service;
create database twinte_session_service;
create database twinte_user_service;